POST http://localhost:3000/auth/sign-up
Content-Type: application/json

{
  "username": "shahab13",
  "email": "shahab13@example.com",
  "password": "P@ssw0rd123",
  "confirmPassword": "P@ssw0rd123"
}
###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "shahab13",
  "password": "P@ssw0rd123"
}


###
POST http://localhost:3000/users/fe12ac60-ecba-436d-8fbc-5269a816e735/follow/bb09c733-484f-40b4-bdf6-e923931eefcb
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoic2hhaGFiMTIiLCJpYXQiOjE3MjM4NDc3NTcsImV4cCI6MTcyMzg1MTM1N30.sg2MbpQII9Jn8nty8SmvwE8_aqY7M-PtrMgMYQ_mzvo
{
  "first_name": "john",
  "last_name": "Doe",
  "bio": "I am John Doe. A fictional character.",
  "is_private": true,
  "email": "john_doe@gmail.com",
  "password": "Pass1234",
  "confirmPassword": "Pass1234"
}



###
GET  http://localhost:3000/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNoYWhhYjEzIiwiaWF0IjoxNzI0MTg4ODU2LCJleHAiOjE3MjQxOTI0NTZ9.9OubKDQjDVYFywq2SdDKWOD3HhBwog76H_ioKU78wLA


###
POST http://localhost:3000/users/bb09c733-484f-40b4-bdf6-e923931eefcb/follow/fe12ac60-ecba-436d-8fbc-5269a816e735
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoic2hhaGFiMTMiLCJpYXQiOjE3MjM4NzE0NzYsImV4cCI6MTcyMzg3NTA3Nn0.EX9Gex0l7dPGOKnJKv8edMb3Tc3uYy-GsjelB7fjalU

###
DELETE  http://localhost:3000/users/bb09c733-484f-40b4-bdf6-e923931eefcb/unfollow/fe12ac60-ecba-436d-8fbc-5269a816e735
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoic2hhaGFiMTMiLCJpYXQiOjE3MjM4NTgzNzQsImV4cCI6MTcyMzg2MTk3NH0.Ra0lJMkKTgFDGhz4cDFiSeRz-xmjjyFKrOAnTx07zHk